package chap8;

public class Exception1 {

	public static void main(String[] args) {

		int a = 9;
		int b = 2;
		int[] arr = new int[10];
		try {
			System.out.println("a / b = " + a / b);
			arr[a] = 100;
			System.out.println("arr[a] = " + arr[a]);
		} catch(ArithmeticException e) {
			System.out.println("0으로 나눌 수 없습니다");
		} catch(ArrayIndexOutOfBoundsException e) {
			System.out.println("배열의 첨자를 벗어났습니다");
		} finally {
			System.out.println("처리가 종료 되었습니다");
		}
	}

}
